### PR TITLE
Bookcreator

### PR DESCRIPTION
**Pull request by Klap-in**
===Work in progress===
Just for enabling discussion and reviewing changes at a central place.

=== Goal===
- implement an export action which can export multiple wiki articles in one ODT file.

This action can be initiated by the Bookcreator plugin's interface.

### CODE REVIEW

**Comment by Klap-in** [comment]
With c356209 I added also some small changes, which require review, and can be included in css-template as well.

**Comment by Klap-in** [comment]
General tip: 
Instead using directly $_GET and $_POST, it is possible in DokuWiki to use a INPUT object, assigned to global $INPUT. See https://www.dokuwiki.org/devel:request_vars, this will handle some input cleaning and setting defaults when empty.

**Comment by Klap-in** [comment]
A first working draft. Currently using some switches for deciding if it is handles as book.

Idea: creating 2nd renderer: renderer_plugin_odt_book
(requires renaming: renderer_plugin_odt to renderer_plugin_odt_page)

**Comment by Klap-in** [comment]
Introduced a separated renderer for odt book creation which extends page renderer.

Possible issue, not tested yet (see also:
Existance of old renderer.php let DokuWiki not discover more renderer components in /renderer/ directory.
Fix: add mechanism to action.php which will rename always `[pluginfolder]/renderer.php` to `[pluginfolder]/renderer.php.old`

Significant issue:
p_cached_output() (used in action.php) caches the xml of every rendered page. However the e.g. autostyles used in the original renderer action, aren't generated if a cache was used. Another issue is that images aren't moved into the odt-file if the cache is used.

Solution directions:
- only cache the final complete odtfile (not difficult, however means cache will expire relatively fast for large numbers of pages and regularly edited pages)
- introduced very advanced caching which knows which files should be included in package and pickup numbering at the right offset for every included wikipage. (difficult, very complex caching, but can gain performance)

other ideas?

Question:
@LarsGit223 could you have a look at my code structure?

**Comment by Klap-in** [comment]
Question:
Do you prefer pagebreaks between subsequent wikiarticles in a odt-book?

**Comment by LarsGit223** [comment]
Sorry, I'm on business travel and can't check your code this week.

**Comment by LarsGit223** [comment]
> Do you prefer pagebreaks between subsequent wikiarticles in a odt-book?

The question is what the users would like. Maybe it should be a config option?

**Comment by Klap-in** [comment]
The dw2pdf plugin adds pagebreaks between the articles. So I tend to do that here as well, without a config option. However, I remember someone requesting for none pagebreaks: https://github.com/Klap-in/dokuwiki-plugin-bookcreator/issues/48

**Comment by LarsGit223** [comment]
> Solution directions:
    only cache the final complete odtfile (not difficult, however means cache will expire relatively fast for large numbers of pages and regularly edited pages)
    introduced very advanced caching which knows which files should be included in package and pickup numbering at the right offset for every included wikipage. (difficult, very complex caching, but can gain performance)

I would choose the first option, the second sounds very complicated. But I have to admit that I do not know much about the caching in DokuWiki.

One thing I noticed when playing around with bookcreator/dw2pdf is that caching can allow a user to receive forbidden content/pages if a user with higher permissions previously exported a book. If the user with lower permissions gets the cached version of the book then it might also include pages to which the user wouldn't have any access.

**Comment by LarsGit223** [comment]
> could you have a look at my code structure?

Looks good to me at first sight :thumbsup:
Do you require any help on ODT specific things?

**Comment by Klap-in** [comment]
That caching issue with dw2pdf (and thus also now with this plugin) was mentioned recently at the dw2pdf by others as well. So at least it requires clear communication.

I will see if I can add a minimal check somewhere...

**Comment by Klap-in** [comment]
I think the ODT book export should be fine now. I cannot remember any points of attention.
So if you test it, and see if it fulfills the expectations, then it is done for me.

**Comment by Klap-in** [comment]
The only think I have to test, and probably fix, is the change from one renderer to two renderers, while updating via the Extension Manager. Probably, if someone updates with the extension manager, he/she will still use the old renderer, not the two new ones.

**Comment by Klap-in** [comment]
This PR is how against the master branch, but look at the comparison (https://github.com/LarsGit223/dokuwiki-plugin-odt/compare/css-template...bookcreator) I think it makes more sense to merge with the css-template branch.

What do you like?

**Comment by LarsGit223** [comment]
Hi Klap-in,
I made a new release yesterday and I planned that the bookcreator feature should be release next. 

There is still a lot of work to do for the CSS templates. I did not change anything on that branch since I created the bookcreator branch from it.

So I would prefer merging the bookcreator branch to master. If the bookcreator feature is stable enough I don't want to hold it back until CSS templates are working.

What do you think?

Greetings,
Lars

**Comment by Klap-in** [comment]
So it is fine that the changes already included from the csstemplate branch in this branch are merged into the master branch?

I tested the change from renderer.php to renderer/[component].php. It works well, even if the old renderer.php is left.

**Comment by LarsGit223** [comment]
Yes, see commit https://github.com/LarsGit223/dokuwiki-plugin-odt/commit/9e2a4b921943027edd4b39cac842f64565280b54. In that commit I deleted the CSS template specific code in the bookcreator branch.

All other changes that you got in the bookcreator branch is "only" refactored/redesigned code which should not change the behaviour/functionality of the plugin. If it does, I would call it a bug which needs to be fixed.

**Comment by Klap-in** [comment]
Fixed the addition of pagebreak after the last page.

**Comment by LarsGit223** [comment]
I'll finish work for today.

I did check some test exports with my usual test pages. Normal export doesn't seem to be broken.

But I found out that ODT template based export is not working anymore because function determineMode() in page.php always returns mode 'scratch' even if this->template is set.

Also noticed that the call '$this->ZIP->Compress(null, $temp_dir, null);' doesn't work anymore with the new ZIP class (in file ODTTemplateDH.php).

I will address this issues tomorrow.

**Comment by LarsGit223** [comment]
Ok, the problem is not in the '$this->ZIP->Compress' call. The whole problem is because $this->template is not set in document_start() yet and so the template file name is empty when setting it by calling '$this->docHandler->setTemplate($this->template);'.

So the ODT template file can not be extracted.

The problem is caused by my re-design. Before my re-design $this->template was used in document_end(), not earlier. Now I already use it in document_start(). That is too early when setting the template by the syntax extension defined syntax.php.

Hmmm...I have to think about a way how to change that without throwing away the DocHandler stuff.

**Comment by Klap-in** [comment]
Where do you check the metadata for the template set by the syntax?
I changed the look-up in the action component to: https://github.com/LarsGit223/dokuwiki-plugin-odt/blob/master/action.php#L67
but I don't see where you checked it in the renderer.

**Comment by Klap-in** [comment]
What are you loading here? 
```php
DOKU_PLUGIN . $plugin_name.'/tpl/' . $template . '/style.css'
                    => DOKU_BASE . 'lib/plugins/'.$plugin_name.'/tpl/' . $template . '/',
```
https://github.com/LarsGit223/dokuwiki-plugin-odt/blob/bookcreator/helper/dwcssloader.php#L63

Does lib/plugins/<pluginname>/tpl/<template> exist? Or should the user create that manually?

**Comment by Klap-in** [comment]
Ah, I see you overwrite the `template` attribute of the renderer, to get the template from the syntax:
https://github.com/LarsGit223/dokuwiki-plugin-odt/blob/master/syntax.php#L104

You can fix this by using the p_get_metadata, like: https://github.com/LarsGit223/dokuwiki-plugin-odt/blob/bookcreator/action.php#L46
(technical note:The metadata renderer is runned and cached independently from the odt-renderer. And depends on the same instructions as input as the odt-renderer, so has the same info.)

**Comment by LarsGit223** [comment]
Thanks! Works again now.

I just did my first bookcreator export to ODT. I created a book of test pages using the following plugins with ODT export:
- wrap
- typography
- emphasis
- exttab3

All pages were exported correctly, looks good. :clap:
I think I will merge bookcreator branch to master this weekend.

**Comment by LarsGit223** [comment]
I just merged the bookcreator branch to master :-)

**Comment by Klap-in** [comment]
Huh, how did you merge? by an manual approach? this pull request was left open..

**Comment by Klap-in** [comment]
Nice to build this feature together :+1: 
It was for me good to handle due to the code refactoring you were doing. Especially the last refactor you added was helpful for me. Keep this good work going!

**Comment by LarsGit223** [comment]
Yes, sorry. Just forgot the open pull-request. Would have been easier of course. I merged on the command line.

Thanks. Working with you was very cooperative.

I will leave the bookcreator in the master branch for a while. I want to work on the following things before releaseing it:
- add a table of contents
- maybe a config option for pagebreak yes/no
- check for the locallink as you mentioned in earlier posts

**Comment by Klap-in** [comment]
For locallinks, I used in the dw2pdf plugin a query to the (singleton) action component for obtaining the page list of the exported book.
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/action.php#L652

Applied in: https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/blob/master/renderer.php#L156

**Comment by LarsGit223** [comment]
Thanks! Works like a bomb.
I implemented/changed the locallinks (branch master). Internal links will be next.

**Comment by LarsGit223** [comment]
@Klap-in
As mentioned before I already merged the code to master. Do you agree to close this pull-request?

**Comment by Klap-in** [comment]
Of course.

**Pull request closed without merging**
