### PR TITLE
duplicated line in lang file

### PR DESCRIPTION
**Pull request by Klap-in**
This gives troubles in Translation Tool as well.
Wondering if the start of the string at a new line is accepted by the translation tool, but first try is to check  if this is already sufficient.

### CODE REVIEW

**Comment by LarsGit223** [comment]
Thanks. Didn't see that one.

I got 2 error messages on re-registering yesterday but could not find where they are coming from. Did you see these two:
```
Filename: de/settings.php
Line: 20
Message: No code execution allowed. 
```

```
Filename: de-informal/lang.php
Line: 33
Message: Content won&#039;t start with a string.
```

**Comment by Klap-in** [comment]
PR #191 should solve line 20. Was that PR already merged when you re-registered the odt plugin?
This PR should address the issue at line 33, but was the my minimal approach for this issue. Maybe more is needed...

**Comment by Klap-in** [comment]
I see the translation tool shows now the translations. So most is fine now :)

**Comment by LarsGit223** [comment]
Yes, it was already merged. Let's hope that that was all. Thanks.

**Pull request merged**
