### PR TITLE
Check acl, continues export with book_skipforbiddenpages=1 is set

### PR DESCRIPTION
**Pull request by Klap-in**
Default it shows a message which warns that selection contains acl protected pages.
To continue the url parameter book_skipforbiddenpages=1 is required.

### CODE REVIEW

**Comment by Klap-in** [comment]
This requires some testing, ...I have fixed already some regressions.

**Comment by LarsGit223** [comment]
Hi Gerrit,
is your testing finished. Should/can I merge this now?

**Comment by Klap-in** [comment]
Could you test this as well? It breaks backward compatibility if there are pages in selection that are not allowed for users (these cases require additional url parameter to continue)

Related to https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/pull/233

**Comment by LarsGit223** [comment]
I will do some testing as soon as I got time for it.
This can take a few days because I am just busy with a little re-design/re-factoring.

**Comment by LarsGit223** [comment]
I think I will have time next week to test it.

One question ahead:
If I understand it right I need to test with bookcreator branch **checking** and ODT branch **forbidden**, right?

**Comment by Klap-in** [comment]
Bookcreator plugin is now updated. The ODT plugin will support it already.
The new version of the bookcreator support also continuing export after acl checking. So it fine to merge this if you have time for it.

**Comment by LarsGit223** [comment]
Ok, merged it. Thanks again for the PR.
Did you already release a new version of the bookcreator plugin or is that still upcoming?

**Comment by Klap-in** [comment]
The Bookceator plugin is published

**Comment by LarsGit223** [comment]
Ok, I just published a maintenance release.

**Pull request merged**
