### PR TITLE
The minor changes from odtexport branch

### PR DESCRIPTION
**Pull request by Klap-in**
See #43

### CODE REVIEW

**Comment by iTStage** [comment]
What remains to modify or adjust as a problem? I wanted to try with the changes, but the file is nearly empty with the "bad permission" message.

**Comment by Klap-in** [comment]
What do you mean?
This are only not odt-export related changes
See the 'bookcreator' branch for the work related to export of books.

**Comment by iTStage** [comment]
I just wanted to know if the export with the book work, or if there are any problems?
I spotted some errors, how do I change them? I know very little github ....

**Comment by Klap-in** [comment]
Short summary: ODT Book export is not working.

**Pull request merged**
