### PR TITLE
Translation update (nl)

### PR DESCRIPTION
**Pull request by dokuwiki-translate**
This pull request contains some translation updates.

### CODE REVIEW

**Comment by LarsGit223** [comment]
Your translation update adds one translation but deletes some older ones. Did you work on an older version? Please correct it.

**Comment by Klap-in** [comment]
That package tag is not supported by the Translation tool. It is ignored when reading the language file and not added again when generating the updated version.

No idea why it seems to use old version (are these indeed recently added strings?) I have to check the log file of the Translation tool for issues. If I don't react, please remember me to do it.

**Comment by LarsGit223** [comment]
No, they are old. Not recently added. I did not commit anything new since months.

I don't know how the translation tool works. There are great differences right now between the master branch and the latest release. Please remember that for the ODT plugin the master branch is the development branch and does not match with the latest release. Could that be the reason?

**Comment by LarsGit223** [comment]
The changed files do not match the master branch so I close this now.

**Pull request closed without merging**
