### PR TITLE
Export ODT

### PR DESCRIPTION
**Pull request by Klap-in**
First start of export action component

Bit mixed up with a couple of minor changes.
These minor changes contains also changes where I'm not 100% sure, e.g. especially some of ace56f416670ac76a741998b2cd2e6ac59d73722

Can you check if I interpreted these correctly?

**Todo:**
 - add something that removes/renames old action.php, otherwise the new action components will never work.
 - action export component is work in progress. I have to investigate how to do multiple wiki articles in one ODT file. 

**Info needed:**
Can the renderer be called repeatly for subsequent files?

Sofar spotted page dependent stuff:
 - [ ] document-start en document-end are per wiki article

### CODE REVIEW

**Comment by LarsGit223** [comment]
> document-start en document-end are per wiki article

Yes, these create the ODT/zip file for a single page actually and so will have to be changed. They just check the `$ID` and the `template` so that needs to be changed to check/work for a list of pages also.

> Info needed:
Can the renderer be called repeatly for subsequent files?

Hmmm, I think currently not because some class variables carry state information whcih need to be re-set first, I guess. See:

```
    var $in_list_item = false;
    var $in_paragraph = false;
    var $in_div_as_frame = 0;
    var $highlight_style_num = 1;
    var $temp_table_column_styles = array ();
    var $temp_table_style = NULL;
    var $temp_in_header = false;
    var $temp_autocols = false;
    var $temp_maxcols = 0;
    var $temp_column = 0;
    var $temp_content = NULL;
    var $temp_cols = NULL;
    var $quote_depth = 0;
    var $quote_pos = 0;
    var $div_z_index = 0;
```

**Comment by Klap-in** [comment]
I see normally Doku_Renderer objects are not a singleton, but the odt renderer is a singleton.
Do you know more about the reasoning for using a singleton?

I'm not sure which structure is desired, but before changing it is useful to know the consequences.

more page dependent stuff:
- [ ] `header()` has a `$hid`, this requires also a prefix with a `$pid` (a cleaned pageid) for the corresponding page. 

What is recommended way in odt renderer to create an unique $pid from a page id?

- [ ] foot notes are numbered, this numbering has to continue at the pages of subsequental wiki articles.
- [] _convert_css_styles

**Comment by Klap-in** [comment]
about locallink(), are internal links in a ODT file not possible? so if there are links to pages, which are included in the ODT, these cannot be linked as well?

 - [ ] If possible, hashes of locallink() needs be unique as well, so prefixed by a $pid

- [ ] Internallinks that points to articles included in the generated ODT has to be changed to links like locallinks()
- [ ] `_odtSpanOpenUseProperties()` counter `style_count` has to continue.
- [ ] one array autostyles required for whole ODT file 
- [ ] `_odtParagraphOpenUseProperties()` paragraph should allready be closed for next article, so `in_paragraph` has not to continue officially for next article..
- [ ] `_odtDivOpenAsFrameUseCSS()` same for `in_div_as_frame`
- [ ] counter `div_z_index` has to continue
- [ ] `_odtTableOpenUsePropertiesonly()` scope of table (so limited to a page) `temp_in_header`
- [ ] same for `temp_table_style`
- [ ] same for `temp_table_column_styles`
- [ ] same for `temp_autocols`
- [ ] same for `temp_cols`
- [ ] `_createTextStyle()` array `styles` has to be shared between pages


- [ ] other page dependent counters...
- [ ] $store - temporary buffer for footnotes, not whole odt-file
- [ ] $manifest  for whole odt-file
- [ ]   var $headers unique headers, whole odt-file
- [ ] $template unique for odt-file, what if more syntaxes are included over the different pages? only the last one is considered or is it possble per page (sounds complicated..)
 - [ ] $fields per whole document. (btw what are these userfields in practice?)
- [ ]  $in_list_item , locally? not whole odt-file
 - [ ]  $temp_maxcols = 0; , locally? not whole odt-file
 - [ ]  var $temp_column = 0; , locally? not whole odt-file
 - [ ]   var $temp_content = NULL; , locally? not whole odt-file
 - [ ] counter $quote_depth, continue for odt-file
 - [ ] storing $quote_pos, keep for whole odt-file

**Comment by LarsGit223** [comment]
> about locallink(), are internal links in a ODT file not possible? so if there are links to pages, which are included in the ODT, these cannot be linked as well?

I think it might currently not be supported/implemented. But I tried it in LibreOffice. You can set a reference to define the position in the document to which you want to link too. And then you can insert a reference to that position on a different page. If you then click on it, it will follow the reference and you are on that page that you amrked with "set reference".

**Comment by LarsGit223** [comment]
> I see normally Doku_Renderer objects are not a singleton, but the odt renderer is a singleton.
Do you know more about the reasoning for using a singleton?

No.

**Comment by LarsGit223** [comment]
> header() has a $hid, this requires also a prefix with a $pid (a cleaned pageid) for the corresponding page.

I don't see a page ID in the function header () of the ODT renderer. I think the bookmark just needs a unique name in "text:name".

**Comment by LarsGit223** [comment]
> What is recommended way in odt renderer to create an unique $pid from a page id?

I think in most cases for the ODT document it doesn't matter how the ID looks like. E.g. as mentioned above the bookmark just needs a unique test. If you look at `_headerToLink()` it searches through the arry headers just to make sure it's unique. But the format of the resulting text string doesn't matter to ODT. So we probably could use a prefix attached with a number to it.

**Comment by LarsGit223** [comment]
> $template unique for odt-file, what if more syntaxes are included over the different pages? only the last one is considered or is it possble per page (sounds complicated..)

No, only one can be used. The template can come from the config, or the request URL or the page content itself. The template can re-define styles by using the same style names as in "styles.xml". E.g. the style "Heading_20_1" defines the style for a level 1 heading. The name "Heading_20_1" is global and ujnique for the whole document. So, it doesn't make sense to use multiple template's in an ODT document because they need to use the same style names as in "styles.xml". But if you overwrite a style name with new content, you change the style for ALL pages. Also, document_end () only works with one template at the end.

**Comment by LarsGit223** [comment]
> $fields per whole document. (btw what are these userfields in practice?)

If I remember right, these are the fields from the plugin:fields.

**Comment by LarsGit223** [comment]
>  $in_list_item , locally? not whole odt-file

I think locally as the list on a wiki page is also ending on the wiki page and can not go across pages. That makes some things simpler for us.

**Comment by LarsGit223** [comment]
> $temp_maxcols = 0; , locally? not whole odt-file
var $temp_column = 0; , locally? not whole odt-file
var $temp_content = NULL; , locally? not whole odt-file

These are temporarily used for the CSS based table functions. So they can be locally used. Usage ends as soon as the table is closed.

If a new table is opened, the variables will be reset.

**Comment by LarsGit223** [comment]
> counter $quote_depth, continue for odt-file
storing $quote_pos, keep for whole odt-file

No, these are temporarily used. The problem is that, if you have a level 3 quotation like ">>>" the function quote_open() is called 3 times. But it does not know in advance if it is ">" or ">>" or ">>>". So, these counters are only used for the lifetime of one quotation line. And then get decreased on quote_close(). So, only temporarily/locally.

**Comment by LarsGit223** [comment]
If you go on with changes you should think about creating a branch for it, as I assume there will be more than just minor changes.

You might also have a look at the branch `csstemplate`. I did move a lot of the renderer code to separate classes in an extra ODT folder. Otherwise I think the file renderer.php is getting to big.

If you like to start from there, let me know. I could create a bookcreator branch for you. And only put the "re-designed" code in there, but I would omit the "csstemplate" specific code which is work in progress.

**Comment by Klap-in** [comment]
css-template looks useful!
It is fine for me to work in a branch of the csstemplate.
I think I will split the commits with the minor changes from this branch and create a separated PR for these. It is not handy to mix this with the export stuff...

- May I become a so-called Contributor on Github to your repository? Then I can create a branch where you can contribute/modify as well.

I don't know how you like to progress with csstemplate or master. Because I will work mainly on the inherited renderer functions I'm not yet affected by your css rewrite. So for me both branches are fine. 
- Which one do you recommendate?

**Comment by Klap-in** [comment]
I saw that $renderer->doc is included into the zip in the end-document() 

I have to introduce a mechanism that allows to collect the content of more pages in the $renderer->doc. While only including it once at the end. I have to decide whether that including should stay in in end-document() or that it is better to move it else where. Ideas are welcome.

Disadvantage is that the page generation is currently an sequential iterator over a page list. So for every page renderer also begin en end-docment() are called. Maybe a global flag is a tric, or a helper that can be called from end-document() for normal page export, but from the action export component as well for multiple pages.

**Comment by LarsGit223** [comment]
I suggest that you progress from csstemplate/create a new branch from csstemplate. In that way we have the re-designed code already in the bookcreator branch and will not have to merge it later.

And I can work on the master for little changes only, if any are required (I'm currently working on finalizing the wrap ODT export).

I suggest to pause my work on css templates and support you with ODT specific stuff, if you like.

I will give you the rights this evening.

**Comment by LarsGit223** [comment]
Hi Klap-in,

I created a branch bookcreator and added you as a collaborator to the ODT plugin.
Be welcomed.

I noticed that I previously did not commit all of my changes to the css-template branch. I did that now, that means the bookcreator has also got this changes. So don't be surprised that there are a lot more changes than before.

Greetings,
Lars

**Comment by Klap-in** [comment]
Ok, thanks! I will have a look.

**Comment by LarsGit223** [comment]
We will have to merge your last changes to this branch also. This will not be easy because of all the changes.

I will now start to do the correction of the `empty() === true` lines. Just wanted to let you know, to prevent that two people work on the same thing.

**Comment by Klap-in** [comment]
I had the plan to cherrypick some commits with minor changes of this pull request and offer these as new pull request.
What do you like to do?

**Comment by LarsGit223** [comment]
I will fix the `empty===true` lines.

**Comment by LarsGit223** [comment]
I think I can merge it all, doesn't seem to be ass bad as expected...

**Comment by Klap-in** [comment]
I have split the minor changes.

**Comment by LarsGit223** [comment]
Branch `bookcreator` should now also have all changes you did in `master`.

**Comment by LarsGit223** [comment]
Just deleted code that only belongs to the branch `css-template`.

I think we can now work on the `bookcreator`branch.

**Comment by Klap-in** [comment]
Ok, thanks!

**Pull request closed without merging**
